### ISSUE TITLE
Wordpress behind ReverseProxy without Certbot

### ISSUE THREAD

**Issue by smilebasti** [Abberit/abberit-cloud#6]
Hi, 
abberit looks great and is easy to use. 
I am using Nginx Reverse Proxy Manager which handles my Certificates. As i try to use it with Abberit i don't assign an https port. Just port 80 or any other. 
With request Abberit adds the port to the domain. Is there a way to stop that? Tried it by manually removing :80 from the domain Because than works.

Thanks

**Comment by MichaelXt** [comment]
Hi, thanks for feedback!
Are you talking about `Host` header added with request? Those are the settings we currently use for nginx:
```
  location / {
    proxy_pass http://$container_host_name;
    proxy_set_header Host {{.ServerName}}:{{.Listen}};
  }
```

**Comment by smilebasti** [comment]
Not sure if it's the header.

The Reverse proxy points to abberit-wordpress on port 80. If i then access the domain/Wordpress through the reverse proxy with https (port 443)  it redirects  the domain to https://domain.com:80. (or any other diffrent port but that is then not open in my firewall).

Usually the port is not added by the Reverse Proxy and just redirects in the background to the specified port in the backend.

Maybe it needs a configuration addition that disables that port 80 is added to the (http) domain. Then i think it work as http is defaulting to port 80.

**Comment by MichaelXt** [comment]
Looks like you are hitting wordpress redirect issue. That happens if you set up the wordpress without the correct HOST header, or changed the port later. In that case, wordpress needs to be told of correct address and port. MySQL entry needs to be updated:
```
update wp_options SET option_value = 'https://your-domain-or-ip:correct-port' where option_id = 1 and option_name = 'siteurl';

update wp_options SET option_value = 'https://your-domain-or-ip:correct-port' where option_id = 2 and option_name = 'home';
```
Do back up your previous values.

Send me email at info@abberit.io so that we can take a look together.
